spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.219.108:3306/jmlim_chat?allowPublicKeyRetrieval=true&useSSL=false
    username: jmlim
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

logging.level:
  org.hibernate.SQL: debug